services:
#    donfelice_csv_import_export.example:
#        class: Donfelice\CSVImportExportBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Donfelice\CSVImportExportBundle\EventListener\CSVAdminUIMenuListener:
        public: true
        tags:
            - { name: kernel.event_subscriber }

    Donfelice\CSVImportExportBundle\Controller\DefaultController:
        arguments:
            $contentService: "@ezpublish.api.service.content"
            #- $locationService: "@ezpublish.api.service.location"
